"use client";

import { CircleAlert, Gift, LoaderCircle, Plus, RotateCw, Target, Trash2, X } from "lucide-react";
import { MobileNav } from "@/components/mobile-nav";
import { FormEvent, useEffect, useRef, useState } from "react";
import { idr } from "@/lib/formatters";
import { ToastContainer, useToast } from "@/components/toast";

type Wishlist = { id: string; name: string; target_amount: number; saved_amount: number; priority: string; target_date: string | null; note: string | null };
const blank = { name: "", targetAmount: "", savedAmount: "0", priority: "medium", targetDate: "", note: "" };

export function WishlistsWorkspace() {
  const { toasts, addToast, removeToast } = useToast();
  const [items, setItems] = useState<Wishlist[]>([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [pendingId, setPendingId] = useState(""); const targetRef = useRef<HTMLInputElement>(null);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/wishlists"); if (!response.ok) throw new Error(); setItems((await response.json()).wishlists); } catch { setError("Data wishlist belum dapat dimuat."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const targetAmount = Number(form.targetAmount); const savedAmount = Number(form.savedAmount); if (!Number.isInteger(targetAmount) || targetAmount <= 0 || !Number.isInteger(savedAmount) || savedAmount < 0 || savedAmount > targetAmount) { setMessage("Target dan tabungan awal harus berupa angka yang valid."); addToast("Data tidak valid", "error"); setSaving(false); targetRef.current?.focus(); return; } try { const response = await fetch("/api/wishlists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, targetAmount, savedAmount }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setForm(blank); setMessage("Wishlist berhasil ditambahkan."); addToast("Wishlist berhasil ditambahkan", "success"); await load(); } catch (createError) { const errorMsg = createError instanceof Error ? createError.message : "Wishlist tidak dapat disimpan."; setMessage(errorMsg); addToast(errorMsg, "error"); } finally { setSaving(false); } }
  async function update(item: Wishlist) { const value = window.prompt(`Tabungan terkumpul untuk ${item.name}`, String(item.saved_amount)); if (value === null) return; const savedAmount = Number(value); if (!Number.isInteger(savedAmount) || savedAmount < 0 || savedAmount > item.target_amount) { setMessage("Tabungan terkumpul harus berada di antara nol dan target."); addToast("Data tidak valid", "error"); return; } setPendingId(item.id); try { const response = await fetch(`/api/wishlists/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ savedAmount, status: savedAmount === item.target_amount ? "purchased" : "active" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const successMsg = savedAmount === item.target_amount ? "Wishlist ditandai selesai." : "Progress wishlist diperbarui."; setMessage(successMsg); addToast(successMsg, "success"); await load(); } catch (updateError) { const errorMsg = updateError instanceof Error ? updateError.message : "Wishlist tidak dapat diperbarui."; setMessage(errorMsg); addToast(errorMsg, "error"); } finally { setPendingId(""); } }
  async function remove(item: Wishlist) { if (!window.confirm(`Hapus wishlist "${item.name}"?`)) return; setPendingId(item.id); try { const response = await fetch(`/api/wishlists/${item.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage("Wishlist dihapus."); addToast("Wishlist dihapus", "success"); await load(); } catch (removeError) { const errorMsg = removeError instanceof Error ? removeError.message : "Wishlist tidak dapat dihapus."; setMessage(errorMsg); addToast(errorMsg, "error"); } finally { setPendingId(""); } }
  const totalTarget = items.reduce((sum, item) => sum + item.target_amount, 0); const totalSaved = items.reduce((sum, item) => sum + item.saved_amount, 0);
  return <><ToastContainer toasts={toasts} onClose={removeToast} /><a className="skip-link" href="#wishlist-list">Lewati ke daftar wishlist</a><header className="mobile-page-bar"><MobileNav /></header><div className="content transaction-page"><div className="page-heading"><div><p className="eyebrow">RENCANA PEMBELIAN</p><h1>Wishlist</h1><p className="muted">Tentukan tujuan belanja tanpa mengganggu kebutuhan utama.</p></div></div><div className="wishlist-summary"><section className="card"><span className="card-label">Total target</span><strong className="stat-number">{idr.format(totalTarget)}</strong></section><section className="card"><span className="card-label">Sudah terkumpul</span><strong className="stat-number positive">{idr.format(totalSaved)}</strong></section><section className="card"><span className="card-label">Progress keseluruhan</span><strong className="stat-number">{totalTarget ? `${Math.round((totalSaved / totalTarget) * 100)}%` : "0%"}</strong></section></div><div className="transaction-layout wishlist-layout">
    <section className="card form-card"><div className="form-title-icon"><Gift size={20} /></div><h2>Tambah wishlist</h2><p className="muted form-intro">Target ini hanya rencana; belum mengurangi saldo wallet.</p><form onSubmit={create}><Field label="Nama barang/tujuan" id="wishlist-name"><input id="wishlist-name" placeholder="Contoh: laptop baru" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Target nominal" id="wishlist-target"><input ref={targetRef} id="wishlist-target" type="number" inputMode="numeric" min="1" step="1" value={form.targetAmount} onChange={(event) => setForm({ ...form, targetAmount: event.target.value })} required /></Field><Field label="Sudah terkumpul" id="wishlist-saved"><input id="wishlist-saved" type="number" inputMode="numeric" min="0" step="1" value={form.savedAmount} onChange={(event) => setForm({ ...form, savedAmount: event.target.value })} required /></Field><div className="form-grid"><Field label="Prioritas" id="wishlist-priority"><select id="wishlist-priority" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option value="high">Tinggi</option><option value="medium">Sedang</option><option value="low">Rendah</option></select></Field><Field label="Target tanggal" id="wishlist-date"><input id="wishlist-date" type="date" value={form.targetDate} onChange={(event) => setForm({ ...form, targetDate: event.target.value })} /></Field></div>{message && <div className="form-message success" role="status"><span>{message}</span><button type="button" aria-label="Tutup pesan" onClick={() => setMessage("")}><X size={16} /></button></div>}<button className="button primary submit-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />}Tambah wishlist</button></form></section>
    <section className="card list-card" id="wishlist-list"><div className="section-header"><div><h2>Daftar wishlist</h2><p className="muted">{items.length} tujuan aktif</p></div><Target size={20} className="section-icon" /></div>{loading ? <div className="state-panel"><LoaderCircle className="spin" size={24} />Memuat wishlist...</div> : error ? <div className="state-panel error"><CircleAlert size={24} /><strong>Gagal memuat data</strong><span>{error}</span><button className="button subtle" onClick={() => void load()}><RotateCw size={16} />Coba lagi</button></div> : items.length === 0 ? <div className="state-panel"><Gift size={24} /><strong>Belum ada wishlist</strong><span>Tambahkan tujuan pembelian pertamamu.</span></div> : <div className="wishlist-list">{items.map((item) => { const progress = Math.min(100, Math.round((item.saved_amount / item.target_amount) * 100)); return <article className="wishlist-row" key={item.id}><div className={`priority-dot ${item.priority}`} title={`Prioritas ${item.priority}`} /><div className="planned-info"><strong>{item.name}</strong><small>{item.target_date ? `Target ${item.target_date}` : "Tanpa target tanggal"} · Prioritas {item.priority}</small><div className="progress-track"><i style={{ width: `${progress}%` }} /></div></div><div className="planned-amount"><strong>{progress}%</strong><small>{idr.format(item.saved_amount)} / {idr.format(item.target_amount)}</small></div><button className="button subtle wishlist-update" disabled={pendingId === item.id} onClick={() => void update(item)}>{pendingId === item.id ? <LoaderCircle className="spin" size={15} /> : <Target size={15} />}Update</button><button className="icon-button danger" aria-label={`Hapus ${item.name}`} onClick={() => void remove(item)}><Trash2 size={17} /></button></article>; })}</div>}</section>
  </div></div></>;
}
function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>; }
