"use client";

import { Banknote, CircleAlert, CreditCard, Landmark, LoaderCircle, Plus, RotateCw, Smartphone, WalletCards, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import { idr } from "@/lib/formatters";
import { MobileNav } from "@/components/mobile-nav";

type Wallet = { id: string; name: string; type: string; currency: string; starting_balance: number; balance: number };
const blank = { name: "", type: "bank", startingBalance: "0" };

export function WalletsWorkspace() {
  const [wallets, setWallets] = useState<Wallet[]>([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const balanceRef = useRef<HTMLInputElement>(null);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/wallets"); if (!response.ok) throw new Error(); setWallets((await response.json()).wallets); } catch { setError("Data wallet belum dapat dimuat."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const startingBalance = Number(form.startingBalance); if (!Number.isInteger(startingBalance)) { setMessage("Saldo awal harus berupa angka bulat."); setSaving(false); balanceRef.current?.focus(); return; } try { const response = await fetch("/api/wallets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, startingBalance }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setForm(blank); setMessage("Wallet berhasil ditambahkan."); await load(); } catch (createError) { setMessage(createError instanceof Error ? createError.message : "Wallet tidak dapat disimpan."); } finally { setSaving(false); } }
  const total = wallets.reduce((sum, wallet) => sum + wallet.balance, 0);
  return <><a className="skip-link" href="#wallet-list">Lewati ke daftar wallet</a><header className="mobile-page-bar"><MobileNav /></header><div className="content transaction-page"><div className="page-heading"><div><p className="eyebrow">SUMBER DANA</p><h1>Wallet</h1><p className="muted">Kelola rekening, uang tunai, e-wallet, dan kreditmu.</p></div></div><div className="wallet-total card"><span>Total seluruh wallet</span><strong>{idr.format(total)}</strong><small>{wallets.length} wallet aktif</small></div><div className="transaction-layout wallet-layout">
    <section className="card form-card"><div className="form-title-icon"><WalletCards size={20} /></div><h2>Tambah wallet</h2><p className="muted form-intro">Saldo awal menjadi dasar perhitungan sebelum transaksi.</p><form onSubmit={create}><Field label="Nama wallet" id="wallet-name"><input id="wallet-name" placeholder="Contoh: BCA Utama" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Tipe" id="wallet-type"><select id="wallet-type" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="bank">Bank</option><option value="cash">Tunai</option><option value="ewallet">E-wallet</option><option value="credit">Kredit / paylater</option></select></Field><Field label="Saldo awal" id="wallet-balance"><input ref={balanceRef} id="wallet-balance" type="number" inputMode="numeric" step="1" value={form.startingBalance} onChange={(event) => setForm({ ...form, startingBalance: event.target.value })} required /></Field>{message && <div className="form-message success" role="status"><span>{message}</span><button type="button" aria-label="Tutup pesan" onClick={() => setMessage("")}><X size={16} /></button></div>}<button className="button primary submit-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />}Tambah wallet</button></form></section>
    <section className="card list-card" id="wallet-list"><div className="section-header"><div><h2>Daftar wallet</h2><p className="muted">Saldo dihitung dari seluruh transaksi</p></div><WalletCards size={20} className="section-icon" /></div>{loading ? <div className="state-panel"><LoaderCircle className="spin" size={24} />Memuat wallet...</div> : error ? <div className="state-panel error"><CircleAlert size={24} /><strong>Gagal memuat data</strong><span>{error}</span><button className="button subtle" onClick={() => void load()}><RotateCw size={16} />Coba lagi</button></div> : <div className="wallet-grid">{wallets.map((wallet) => <article className="wallet-card" key={wallet.id}><div className={`wallet-icon ${wallet.type}`}>{wallet.type === "cash" ? <Banknote size={19} /> : wallet.type === "ewallet" ? <Smartphone size={19} /> : wallet.type === "credit" ? <CreditCard size={19} /> : <Landmark size={19} />}</div><div><small>{wallet.type === "ewallet" ? "E-wallet" : wallet.type === "credit" ? "Kredit / paylater" : wallet.type}</small><h2>{wallet.name}</h2></div><strong className={wallet.balance < 0 ? "negative" : ""}>{idr.format(wallet.balance)}</strong><span>Saldo awal {idr.format(wallet.starting_balance)}</span></article>)}</div>}</section>
  </div></div></>;
}
function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>; }
