"use client";

import { BarChart3, Bitcoin, CircleAlert, Coins, LoaderCircle, Plus, RotateCw, Trash2, TrendingDown, TrendingUp, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import { idr } from "@/lib/formatters";
import { MobileNav } from "@/components/mobile-nav";

type Asset = { id: string; name: string; category: string; asset_type: string; quantity: number; purchase_value: number; current_value: number; valuation_date: string | null; note: string | null };
const blank = { name: "", category: "investasi", assetType: "stock", quantity: "1", purchaseValue: "", currentValue: "", valuationDate: new Date().toISOString().slice(0, 10), note: "" };

export function AssetsWorkspace() {
  const [assets, setAssets] = useState<Asset[]>([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [pendingId, setPendingId] = useState(""); const valueRef = useRef<HTMLInputElement>(null);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/assets"); if (!response.ok) throw new Error(); setAssets((await response.json()).assets); } catch { setError("Data aset belum dapat dimuat."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const payload = { ...form, quantity: Number(form.quantity), purchaseValue: Number(form.purchaseValue), currentValue: Number(form.currentValue) }; if (payload.quantity <= 0 || !Number.isInteger(payload.purchaseValue) || payload.purchaseValue < 0 || !Number.isInteger(payload.currentValue) || payload.currentValue < 0) { setMessage("Jumlah dan nilai aset harus berupa angka yang valid."); setSaving(false); valueRef.current?.focus(); return; } try { const response = await fetch("/api/assets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setForm(blank); setMessage("Aset berhasil ditambahkan."); await load(); } catch (createError) { setMessage(createError instanceof Error ? createError.message : "Aset tidak dapat disimpan."); } finally { setSaving(false); } }
  async function update(asset: Asset) { const value = window.prompt(`Nilai terbaru ${asset.name}`, String(asset.current_value)); if (value === null) return; const currentValue = Number(value); if (!Number.isInteger(currentValue) || currentValue < 0) { setMessage("Nilai terbaru harus berupa angka bulat positif."); return; } setPendingId(asset.id); try { const response = await fetch(`/api/assets/${asset.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentValue, valuationDate: new Date().toISOString().slice(0, 10) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage("Nilai aset diperbarui."); await load(); } catch (updateError) { setMessage(updateError instanceof Error ? updateError.message : "Nilai tidak dapat diperbarui."); } finally { setPendingId(""); } }
  async function remove(asset: Asset) { if (!window.confirm(`Hapus aset "${asset.name}"?`)) return; setPendingId(asset.id); try { const response = await fetch(`/api/assets/${asset.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage("Aset dihapus."); await load(); } catch (removeError) { setMessage(removeError instanceof Error ? removeError.message : "Aset tidak dapat dihapus."); } finally { setPendingId(""); } }
  const total = assets.reduce((sum, asset) => sum + asset.current_value, 0); const gain = assets.reduce((sum, asset) => sum + asset.current_value - asset.purchase_value, 0);
  return <><a className="skip-link" href="#asset-list">Lewati ke daftar aset</a><header className="mobile-page-bar"><MobileNav /></header><div className="content transaction-page"><div className="page-heading"><div><p className="eyebrow">KEKAYAAN BERSIH</p><h1>Aset & investasi</h1><p className="muted">Nilai saham, crypto, dan aset lain diperbarui manual.</p></div></div><div className="asset-summary"><section className="card"><span className="card-label">Total nilai aset</span><strong className="stat-number">{idr.format(total)}</strong></section><section className="card"><span className="card-label">Untung / rugi</span><strong className={`stat-number ${gain >= 0 ? "positive" : "negative"}`}>{gain >= 0 ? "+" : ""}{idr.format(gain)}</strong></section><section className="card"><span className="card-label">Jumlah aset</span><strong className="stat-number">{assets.length}</strong></section></div><div className="transaction-layout asset-layout">
    <section className="card form-card"><div className="form-title-icon"><BarChart3 size={20} /></div><h2>Tambah aset</h2><p className="muted form-intro">Isi total modal dan total nilai saat ini, bukan harga per unit.</p><form onSubmit={create}><Field label="Nama atau kode" id="asset-name"><input id="asset-name" placeholder="Contoh: BBCA atau Bitcoin" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Jenis" id="asset-type"><select id="asset-type" value={form.assetType} onChange={(event) => setForm({ ...form, assetType: event.target.value })}><option value="stock">Saham</option><option value="crypto">Crypto</option><option value="property">Properti</option><option value="vehicle">Kendaraan</option><option value="other">Lainnya</option></select></Field><Field label="Jumlah unit" id="asset-quantity"><input id="asset-quantity" type="number" inputMode="decimal" min="0.00000001" step="any" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} required /></Field><Field label="Total modal" id="asset-purchase"><input id="asset-purchase" type="number" inputMode="numeric" min="0" step="1" value={form.purchaseValue} onChange={(event) => setForm({ ...form, purchaseValue: event.target.value })} required /></Field><Field label="Nilai saat ini" id="asset-current"><input ref={valueRef} id="asset-current" type="number" inputMode="numeric" min="0" step="1" value={form.currentValue} onChange={(event) => setForm({ ...form, currentValue: event.target.value })} required /></Field>{message && <div className="form-message success" role="status"><span>{message}</span><button type="button" aria-label="Tutup pesan" onClick={() => setMessage("")}><X size={16} /></button></div>}<button className="button primary submit-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />}Tambah aset</button></form></section>
    <section className="card list-card" id="asset-list"><div className="section-header"><div><h2>Portofolio</h2><p className="muted">Klik nilai untuk memperbarui valuasi</p></div><Coins size={20} className="section-icon" /></div>{loading ? <div className="state-panel"><LoaderCircle className="spin" size={24} />Memuat aset...</div> : error ? <div className="state-panel error"><CircleAlert size={24} /><strong>Gagal memuat data</strong><span>{error}</span><button className="button subtle" onClick={() => void load()}><RotateCw size={16} />Coba lagi</button></div> : assets.length === 0 ? <div className="state-panel"><BarChart3 size={24} /><strong>Belum ada aset</strong><span>Tambahkan saham, crypto, atau aset pertama.</span></div> : <div className="asset-list">{assets.map((asset) => { const assetGain = asset.current_value - asset.purchase_value; return <div className="asset-row" key={asset.id}><div className={`asset-icon ${asset.asset_type}`}>{asset.asset_type === "crypto" ? <Bitcoin size={19} /> : <BarChart3 size={19} />}</div><div className="planned-info"><strong>{asset.name}</strong><small>{asset.asset_type} · {asset.quantity} unit</small></div><button className="asset-value" disabled={pendingId === asset.id} onClick={() => void update(asset)}><strong>{idr.format(asset.current_value)}</strong><small className={assetGain >= 0 ? "positive" : "negative"}>{assetGain >= 0 ? <TrendingUp size={12} /> : <TrendingDown size={12} />}{idr.format(assetGain)}</small></button><button className="icon-button danger" aria-label={`Hapus ${asset.name}`} onClick={() => void remove(asset)}><Trash2 size={17} /></button></div>; })}</div>}</section>
  </div></div></>;
}
function Field({ label, id, children }: { label: string; id: string; children: React.ReactNode }) { return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>; }
